name: xmlrpc
version: 1.0.9
authors:
- Kirill Vergun <pub.dartlang.org@o-nix.me>
- AurÃ©lien Ballier <aurelien.ballier@cyclonit.com>
description: Useful helper classes for the XML-RPC parsing.
homepage: https://github.com/o-nix/dart-xmlrpc
environment:
  sdk: '>=1.0.0'
documentation: http://o-nix.me/dart-xmlrpc/xmlrpc.html
dependencies:
  crypto: '>=0.9.0'
  http: '>=0.9.2+3'
  intl: '>=0.9.4'
  xml: '>=2.1.3'
dev_dependencies:
  unittest: any
